export const AUTH = {
  AUTHENTICATED: "AUTHENTICATED",
  LOGGED_OUT: "LOGGED_OUT",
  GET_AUTH_STATUS: "GET_AUTH_STATUS",
  GET_USER_FIRST_NAME: "GET_USER_FIRST_NAME",
  GET_USER_EMAIL: "GET_USER_EMAIL",
  GET_USER_LAST_NAME: "GET_USER_LAST_NAME",

  SET_USER_FIRST_NAME: "SET_USER_FIRST_NAME",
  SET_USER_LAST_NAME: "SET_USER_LAST_NAME",
  SET_USER_EMAIL_ADDRESS: "SET_USER_EMAIL_ADDRESS",
  SET_USER_GROUP_TYPE: "SET_USER_GROUP_TYPE",
  SET_USER_TYPE: "SET_USER_TYPE",
  SET_USER_PASSWORD: "SET_USER_PASSWORD",

  GET_ALL_USERS_REQUEST: "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
};

export const NAV = {
  SET_CURRENT_TAB: "SET_CURRENT_TAB",
  SET_CURRENT_CLIENT_TAB: "SET_CURRENT_CLIENT_TAB",
};
