const SERVICE = {
  SET_NEW_SERVICE_REQUEST: "SET_NEW_SERVICE_REQUEST",
  SET_NEW_SERVICE_REQUEST_SUCCESS: "SET_NEW_SERVICE_REQUEST_SUCCESS",

  GET_SERVICE_REQUESTS: "GET_SERVICE_REQUESTS",
  GET_SERVICE_REQUESTS_SUCCESS: "GET_SERVICE_REQUESTS_SUCCESS",
};

export default SERVICE;
